version: '3.0'

services:
  mydata-postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydata_postgres
    ports:
      - 4000:5432

  app-container:
    build:
      context: ./webapp
      dockerfile: dockerfile

    ports:
      - 5500:5500

  data-extract-container:
    image: apache/airflow:2.9.0-python3.10
    volumes:
      - ./dags:/opt/airflow/dags
      - ./airflow-data/events:/var/tmp
      - ./airflow-data/wikimedia:/tmp/var
      - ./reference_config:/opt/airflow
    ports:
      - 8080:8080

    command: bash -c '(airflow db init && airflow users create --username admin --password admin --firstname viet --lastname lam --role Admin --email vietlam050607@gmail.com); airflow webserver & airflow scheduler'

volumes:
  dags:
  airflow-data:
#  reference_config: check file config de xem execution_date cua tung ngay